#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Oct 14 06:15:54 PDT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=0
shaderPack=
