#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Nov 18 05:30:07 PST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=BSL-optimized_1.zip
